#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  7 11:26:50 2016

@author: danielbillmann
"""

import os

os.getcwd()
with open("testing.txt", "a") as file:
    file.write("\nGnarly bro.....")
    
os.rename("testing.txt", "testing.csv")

with open("text.txt", "w") as file:
    file.write("\nTest")

os.rename("text.txt", "test.csv")

name = os.path.splitext("testing.csv")
print(name)


